### ISSUE TITLE
`Deserialize` implementation of `JsonWebAlgorithm` always deserializes a `&str`

### ISSUE THREAD

**Issue by Erik1000** [minkan-chat/jose#38]
This leads to a failure when deserializing from a owned type like `serde_json::Value`. Introduced in <https://github.com/minkan-chat/jose/blob/main/src/macros.rs#L308>

**Comment by Stupremee** [comment]
This will actually fixed in my pull request for the Test Suite. Look at the proper-test-suite branch

**Comment by Erik1000** [comment]
Fixed in 8083bd2a251a4fd83ea5109ea68166d7b24b52f2
